import Image from "next/image";
import { notFound } from "next/navigation";
import { Header } from "@/components/Header";
import { performances } from "@/lib/data/demo";

export function generateStaticParams(){ return performances.map(p=>({slug:p.slug})); }

export default async function PlayerProfile({ params }: { params: Promise<{ slug:string }> }) {
  const {slug}=await params; const p=performances.find(x=>x.slug===slug); if(!p) notFound();
  return <main><Header /><section className="bg-hornet-950 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[320px_1fr] lg:px-8"><div className="relative aspect-[4/5] overflow-hidden rounded-4xl"><Image src={p.photo} alt="Demo athlete placeholder" fill className="object-cover"/></div><div className="self-end pb-4"><p className="text-xs font-black uppercase tracking-[.22em] text-gold-300">{p.sacYears}</p><h1 className="athletic-title mt-3 text-6xl sm:text-8xl">{p.name}</h1><p className="mt-4 text-lg font-bold text-white/70">{p.position} · {p.team} · {p.level}</p><p className="mt-5 max-w-2xl text-sm text-white/45">Demo profile. Hometown and draft information are intentionally omitted until verified provider data is connected.</p></div></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-card lg:col-span-2"><p className="text-xs font-black uppercase tracking-[.18em] text-hornet-700">Yesterday</p><h2 className="mt-3 text-3xl font-black">{p.result} · {p.opponent}</h2><p className="stat-tabular mt-5 text-2xl font-black text-hornet-950">{p.yesterday}</p><p className="mt-4 leading-7 text-neutral-600">{p.summary}</p></div><div className="rounded-3xl bg-gold-500 p-6 text-hornet-950"><p className="text-xs font-black uppercase tracking-[.18em]">Season stats</p><p className="mt-4 text-2xl font-black">{p.season}</p><p className="mt-4 text-sm">Production profile pages will render full hitter or pitcher stat tables from normalized season records.</p></div></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{["Recent Games","Latest News","Videos"].map((x,i)=><section key={x} className="rounded-3xl border border-black/5 bg-white p-6"><h2 className="text-xl font-black">{x}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{i===0?"Previous 10 verified appearances will be listed here.":i===1?"Source-linked player mentions will appear here.":"Matched embeddable highlights will appear here."}</p></section>)}</div></section></main>;
}
